# Generated by Django 6.0.5 on 2026-05-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_booking_booking_id_booking_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='total_seats',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
